



# hahaha






app: main.c utils.c  # 目标: app，依赖: main.c utils.c(依赖可以不存在)
	gcc -o app main.c utils.c  # 编译命令
    
	git apply  xxx.patch  # 样例

app: main.c utils.c  # 目标: app，依赖: main.c utils.c(依赖可以不存在)




	echo "success build app"
    #（如上格式存在n个）